Updated version to 4.3.19 according to recent changes (added type bas…
sreiter/ProMesh pull request #7
Opened 2020-01-30 09:22 UTC by mastep84

…ed volume selection).

2020-01-30 20:34 UTC, sreiter requested changes
4.3.18 has not yet been released - so this would be the next version. Your changes would ideally go into that version.
Thanks

2020-01-30 20:34 UTC, sreiter commented on recent_changes.txt
> +- added Selection-SelectVolumesByType
Please add your changes to the "Changes and additions" of v 4.3.18, which is the next version which will be released. Please also remove the v 4.3.19 section for now - we will add it later when 4.3.18 is done.
Thanks!

2020-01-30 20:34 UTC, sreiter commented on version.txt
> +4.3.19
Please increase to 4.3.18 instead of 4.3.17.
Thanks!

2020-01-31 08:45 UTC, mastep84 commented
Thank you, applied changes according to your requests.

2020-01-31 12:11 UTC, mastep84 commented
Now also adding ReplaceInFile functionality for UNIX.

2020-01-31 20:14 UTC, sreiter reviewed
Great, thanks!
If it would have been even more comfortable to merge it, if you had created a new the pull request for the docugen related stuff.
Nevertheless, thanks a lot!

2020-01-31 20:14 UTC, merged